import { StyleSheet } from '@react-pdf/renderer';

export const pdfStyles = StyleSheet.create({
  coverPage: {
    backgroundColor: '#1a1a1a',
    padding: 72,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
  },
  coverTitle: {
    fontFamily: 'Playfair Display',
    fontSize: 40,
    color: '#F5A623',
    textAlign: 'center',
    marginBottom: 16,
  },
  coverGenre: {
    fontSize: 12,
    color: '#999',
    textTransform: 'uppercase',
    letterSpacing: 2,
    marginBottom: 8,
  },
  coverChapterLabel: {
    fontSize: 14,
    color: '#ccc',
    marginTop: 32,
  },
  coverBranding: {
    fontSize: 10,
    color: '#555',
    position: 'absolute',
    bottom: 48,
  },
  page: {
    paddingTop: 72,
    paddingBottom: 72,
    paddingLeft: 90,
    paddingRight: 90,
    backgroundColor: '#FDFAF5',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 36,
    borderBottomWidth: 0.5,
    borderBottomColor: '#ddd',
    paddingBottom: 8,
  },
  headerLeft: {
    fontSize: 9,
    color: '#888',
    fontFamily: 'Playfair Display',
    fontStyle: 'italic',
  },
  headerRight: {
    fontSize: 9,
    color: '#888',
  },
  body: {
    fontFamily: 'Playfair Display',
    fontSize: 12,
    lineHeight: 1.9,
    color: '#2C2416',
  },
  paragraph: {
    marginBottom: 12,
    textAlign: 'justify',
  },
  dropCapParagraph: {
    marginBottom: 12,
    textAlign: 'justify',
  },
  dropCap: {
    fontFamily: 'Playfair Display',
    fontSize: 48,
    lineHeight: 0.8,
    color: '#F5A623',
    fontWeight: 'bold',
    float: 'left',
    marginRight: 4,
    marginTop: 4,
  },
  footer: {
    position: 'absolute',
    bottom: 48,
    left: 90,
    right: 90,
    textAlign: 'center',
    fontSize: 9,
    color: '#888',
  },
  authorNoteSeparator: {
    borderTopWidth: 0.5,
    borderTopColor: '#ccc',
    marginTop: 36,
    marginBottom: 16,
  },
  authorNoteTitle: {
    fontSize: 9,
    color: '#888',
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    fontFamily: 'Playfair Display',
    marginBottom: 8,
  },
  authorNoteBody: {
    fontSize: 10,
    color: '#555',
    lineHeight: 1.6,
  },
});
